---
title: "GIS mapping"
author: "Wanda Bodnar"
date: "`r Sys.Date()`"
format:
  html:
    theme:
      light: flatly
      dark: darkly
editor: visual
---


```{=html}
<style>
.quarto-title-block { text-align: center; }
</style>
```


::: {.panel-tabset}

## Introduction
...

## Methods
...

## Results

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Load libraries
library(leaflet)            # interactive maps
library(leaflet.extras)     # extra leaflet functions  
library(leaflet.extras2)    # extra leaflet functions
library(stars)              # for raster and spatiotemporal data
library(esri2sf)            # ArcGIS FeatureServer -> sf
library(leaflet.providers)  # leaflet basemaps
library(sf)                 # spatial data  
library(rnaturalearth)      # Natural Earth basemap

# Leaflet expects WGS84 lon/lat
target_crs <- 4326
```

This map below shows the recent earthquakes around the world and the active fault lines. 

```{r, echo=FALSE, message=FALSE, warning=FALSE}
# Earthquakes
eq <- st_read("https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/2.5_day.geojson", quiet = TRUE) 

# Fault lines
faults <- esri2sf::esri2sf(
  "https://services.arcgis.com/jIL9msH9OI208GCb/ArcGIS/rest/services/Active_Faults/FeatureServer/0",
  where = "1=1") %>%
  st_transform(target_crs)

# Map
leaflet(width = "100%") %>%
  setView(lng = 63, lat = 28, zoom = 2) %>%
  addProviderTiles(providers$CartoDB.DarkMatter, group = "Carto Dark") %>%
  addProviderTiles(providers$CartoDB.Positron, group = "Carto Light") %>%
  addProviderTiles(providers$Esri.WorldImagery, group = "Satellite") %>%
  addPolylines(
    data = faults,
    color = "orange",
    weight = 2,
    group = "Faults") %>%
  addCircleMarkers(
    data = eq,
    color = "red",
    fillOpacity = 1,
    radius = ~mag,
    popup = ~paste("Location:", place, "<br>",
                   "Magnitude:", mag, "<br>",
                   "Date:", as.character(as.POSIXct(time/1000, origin="1970-01-01"))),
    group = "Earthquakes") %>%
  addLayersControl(
    baseGroups = c("Carto Dark","Carto Light", "Satellite"),
    overlayGroups = c("Earthquakes", "Faults"),
    options = layersControlOptions(collapsed = FALSE)) %>%
  addLegend(
    position = "bottomright",
    colors = c("red", "orange"),
    labels = c("Circle size proportional to magnitude", "Fault lines"),
    opacity = 1) %>%
  addResetMapButton() %>%
  addFullscreenControl()
```

(Data source: [U.S. Geological Survey](https://www.usgs.gov/programs/earthquake-hazards/earthquakes))

## Discussion
...

## Conclusion
...